import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E9F1F8',
    paddingTop: 60,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    alignItems: 'center',
    position: 'relative',
  },
  titleText: {
    fontSize: 24,
    fontFamily: 'VarelaRound_400Regular',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 6,
    marginTop: 24,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    paddingTop: 20,
    flexWrap: 'wrap',
  },
  subtitleText: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    fontFamily: 'VarelaRound_400Regular',
  },
  star: {
    position: 'absolute',
    zIndex: 1,
  },
  starEmoji: {
    fontSize: 20,
  },
  toothEmoji: {
    fontSize: 24,
  },
  contentList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  mediumRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 0,
  },
  smallRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  largeCard: {
    width: width - 32,
    height: 150,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    marginBottom: 16,
    marginTop: 16,
  },
  mediumCard: {
    width: (width - 48) / 2,
    height: 200,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
  },
  smallCard: {
    width: (width - 48) / 2,
    height: 100,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
  },
  gradientCard: {
    flex: 1,
    padding: 20,
    justifyContent: 'space-between',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: -5,
  },
  cardContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexDirection: 'column',
  },

  cardTextColumn: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingHorizontal: 0,
    paddingVertical: 8,
  },

  gameTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'VarelaRound_400Regular',
    textAlign: 'left',
    marginBottom: 8,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    lineHeight: 18,
  },
  gameSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.9)',
    fontFamily: 'VarelaRound_400Regular',
    textAlign: 'left',
    lineHeight: 18,
  },
  playButton: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressSection: {
    marginTop: 5,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  progressTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: 'VarelaRound_400Regular',
  },
  progressCards: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  progressCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    marginHorizontal: 4,
    minHeight: 85,
  },
  progressEmoji: {
    fontSize: 24,
    marginBottom: 8,
    textAlign: 'center',
  },
  progressLabel: {
    fontSize: 12,
    color: '#7F8C8D',
    textAlign: 'center',
    fontFamily: 'VarelaRound_400Regular',
    marginBottom: 4,
    lineHeight: 14,
  },
  progressValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
  },

  // Legacy styles for backward compatibility
  filterContainer: {
    paddingBottom: 24,
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  filterPill: {
    backgroundColor: 'none',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 8,
    borderWidth: 2.5,
    borderColor: '#516287',
    justifyContent: 'center',
    alignItems: 'center',
    height: 45,
  },
  activeFilter: {
    backgroundColor: '#EDDFD3',
    borderColor: '#875B51',
  },
  filterText: {
    color: '#333333',
    fontSize: 16,
  },
  activeFilterText: {
    color: '#333333',
    fontSize: 16,
  },
  contentCard: {
    backgroundColor: '#FFFDF6',
    borderRadius: 16,
    padding: 30,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginTop: 5,
  },
  gameCards: {
    flexWrap: 'wrap',
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
  },
  topicText: {
    fontSize: 17,
    color: '#333333',
    flex: 1,
  },
  categoryTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#EDDFD3',
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  categoryText: {
    fontSize: 12,
    color: '#875B51',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: '#333333',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFDF6',
    padding: 10,
  },
  closeButton: {
    alignSelf: 'flex-end',
    marginTop: 52,
    padding: 10,
    marginBottom: 10,
    color: '#333333',
  },
  modalContent: {
    flex: 1,
  },
  contentTitle: {
    fontSize: 28,
    color: '#333333',
    marginBottom: 24,
    alignSelf: 'center',
  },
  contentCategory: {
    fontSize: 18,
    color: '#656B69',
    marginBottom: 25,
  },
  contentImage: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginBottom: 20,
  },
  contentDetails: {
    marginBottom: 30,
  },
  detailItem: {
    flexDirection: 'row',
    marginBottom: 15,
    alignItems: 'flex-start',
  },
  bulletPoint: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#516287',
    marginTop: 8,
    marginRight: 12,
  },
  detailText: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: '#333333',
  },
  searchContainer: {
    paddingHorizontal: 10,
    marginBottom: 16,
    marginTop: 24,
  },
  searchInput: {
    backgroundColor: 'none',
    borderWidth: 2.5,
    borderColor: '#516287',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 16,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 60,
  },
  backButton: {
    padding: 8,
    marginRight: 12,
  },
  headerTextContainer: {
    flex: 1,
  },
  itemCountText: {
    fontSize: 14,
    color: '#666666',
    marginTop: 2,
  },
  errorText: {
    fontSize: 18,
    color: '#333333',
    textAlign: 'center',
    marginTop: 100,
  },
  greetingText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333333',
    textAlign: 'center',
    paddingTop: 20,
  },
});