import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E9F1F8',
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  scroll: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: 28,
    color: '#333333',
    marginBottom: 24,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  progressText: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: '#666666',
  },
  question: {
    fontSize: 22,
    textAlign: 'center',
    marginBottom: 30,
    fontWeight: '600',
    color: '#333333',
    paddingHorizontal: 8,
  },
  option: {
    backgroundColor: '#FFFDF6',
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginHorizontal: 4,
  },
  optionText: {
    fontSize: 17,
    textAlign: 'center',
    color: '#333333',
  },
  correct: {
    backgroundColor: '#A5D6A7',
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  wrong: {
    backgroundColor: '#EF9A9A',
    borderWidth: 2,
    borderColor: '#F44336',
  },
  resultText: {
    fontSize: 20,
    textAlign: 'center',
    marginVertical: 20,
    color: '#333333',
  },
  button: {
    backgroundColor: '#875B51',
    padding: 16,
    marginTop: 12,
    borderRadius: 16,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonText: {
    fontSize: 17,
    textAlign: 'center',
    color: '#FFFDF6',
    fontWeight: '600',
  },
  backButton: {
    position: 'absolute',
    top: 70,
    left: 20,
    zIndex: 1,
    padding: 8,
    backgroundColor: '#FFFDF6',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
});