import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E9F1F8',
  },
  scrollView: {
    flex: 1,
  },
  calendarContainer: {
    backgroundColor: '#ffffff',
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    padding: 10,
    overflow: 'hidden',
  },
  contentContainer: {
    flex: 1,
    padding: 20,
  },
  selectedDateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  appointmentsList: {
    flex: 1,
    marginBottom: 70,
  },
  appointmentCard: {
    backgroundColor: '#FFFDF6',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginTop: 5,
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appointmentInfo: {
    flex: 1,
  },
  timeText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 4,
  },
  locationText: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 2,
  },
  dentistText: {
    fontSize: 14,
    color: '#666666',
  },
  typeTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#EDDFD3',
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  confirmedTag: {
    alignSelf: 'flex-start',
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginTop: 8,
  },
  confirmed: {
    backgroundColor: '#A5D6B0',
  },
  unconfirmed: {
    backgroundColor: '#FFE4BD',
  },
  confirmedText: {
    fontSize: 12,
    color: '#495F4D',
  },
  unconfirmedText: {
    fontSize: 12,
    color: '#78685C',
  },
  typeText: {
    fontSize: 12,
    color: '#875B51',
  },
  noAppointments: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  noAppointmentsText: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
  },
  fab: {
    position: 'absolute',
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    left: '50%',
    marginLeft: -28,
    bottom: 85,
    backgroundColor: '#00adf5',
    borderRadius: 28,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
    container: {
        flex: 1,
        backgroundColor: '#E9F1F8',
    },
    scrollView: {
        flex: 1,
    },
    calendarContainer: {
      backgroundColor: '#ffffff',
      marginHorizontal: 10,
      marginTop: 10,
      borderRadius: 16,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      padding: 10,
      overflow: 'hidden',
    },
    contentContainer: {
        flex: 1,
        padding: 20,
    },
    selectedDateText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 20,
        textAlign: 'center',
    },
    appointmentsList: {
        flex: 1,
        marginBottom: 70,
    },
    appointmentCard: {
        backgroundColor: '#FFFDF6',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        marginTop: 5,
    },
    cardContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    appointmentInfo: {
        flex: 1,
    },
    timeText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333333',
        marginBottom: 4,
    },
    locationText: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 2,
    },
    dentistText: {
        fontSize: 14,
        color: '#666666',
    },
    typeTag: {
        alignSelf: 'flex-start',
        backgroundColor: '#EDDFD3',
        borderRadius: 12,
        paddingVertical: 4,
        paddingHorizontal: 10,
        marginTop: 8,
        marginRight: 8,
    },
    typeText: {
        fontSize: 12,
        color: '#875B51',
    },
    noAppointments: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    noAppointmentsText: {
        fontSize: 16,
        color: '#666666',
        textAlign: 'center',
    },
    fab: {
        position: 'absolute',
        width: 56,
        height: 56,
        alignItems: 'center',
        justifyContent: 'center',
        left: '50%',
        marginLeft: -28,
        bottom: 85,
        backgroundColor: '#00adf5',
        borderRadius: 28,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    modalBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.35)',
    },
    modalContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: '10%',
        transform: [{ translateX:0 }],
        backgroundColor: '#fff',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        borderBottomRightRadius: 16,
        borderBottomLeftRadius: 16,
        padding: 16,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: -2},
        shadowOpacity: 0.25,
        shadowRadius: 8,
        overflow: 'hidden',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
        width: '100%',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#333',
    },
    modalCloseButton: {
        padding: 8,
        alignSelf: 'flex-end',
    },
    modalCloseText: {
        color: '#00adf5',
        fontSize: 16,
        fontWeight: '600',
    },
    modalContent: {
        gap: 12,
    },
    modalDetailRow: {
        flexDirection: 'row',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    modalDetailCancel: {
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    modalDetailLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
        width: 80,
    },
    modalDetailValue: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    modalDetailValueCancel: {
        fontSize: 12,
        color: 'red',
        flex: 1,
        textAlign: 'center'
    },
    formGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
        color: '#333',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        backgroundColor: '#fff',
    },
    submitButton: {
        backgroundColor: '#00adf5',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 20,
    },
    submitButtonDisabled: {
        backgroundColor: '#ccc',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
});

export default styles;
