name: Tooth Mate CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-react-web:
    name: Test React Web (H5)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-dental-chart

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests if available
        run: |
          if ls **/*.test.js 1> /dev/null 2>&1; then
            echo "Running tests..."
            npm test -- --ci
          else
            echo "No test files found. Skipping tests."
          fi

  setup-backend:
    name: Setup Backend Only (No Test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install

      - name: No backend tests yet
        run: echo "No backend tests implemented yet."
